// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwcxvpysjuasutgqhewp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3Y3h2cHlzanVhc3V0Z3FoZXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTE4NDQsImV4cCI6MjA3MjQ2Nzg0NH0.xIlwFvst0UoN47vykpuPjyRsRoS1PJFwmiQJNs-Y9Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});